# Microcosmic God experiment kernel (generated by kaggle/push_run.py).
# Clones the public repo at the pinned branch, runs one simulation with the
# CONFIG below, and leaves results in /kaggle/working for collection.

CONFIG = {
    "branch": "fable-working",
    "profile": "minute",
    "seed": 1,
    "ticks": 8000,
    "wall_seconds": 600.0,
    "harshness": None,
    "neural_grace_ticks": 150,
    "neural_grace_floor": 0.35,
    "modular_fraction": 0.5,
    "modular_max_blocks": 1,
    "structural_rate": 0.06,
    "world_refresh_every": 0,
    "checkpoint_every": 1000,
    "checkpoint_limit": 64,
    "quiet_events": True,
    "log_every": 100,
    "action_search_depth": None,
    "drive_injection_scale": None,
    "tap_cue_threshold": None,
    "tap_cue_drift": None,
    "combine_intent_window_scale": None,
    "exploration_floor": None,
}

import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO = "https://github.com/asystemoffields/microcosmic-god.git"
WORK = Path("/kaggle/working")
SRC = Path("/tmp/mg")


def sh(*cmd: str) -> None:
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)


sh("git", "clone", "--depth", "1", "--branch", CONFIG["branch"], REPO, str(SRC))

args = [
    sys.executable, "-m", "microcosmic_god", "run",
    "--profile", str(CONFIG["profile"]),
    "--seed", str(CONFIG["seed"]),
    "--ticks", str(CONFIG["ticks"]),
    "--wall-seconds", str(CONFIG["wall_seconds"]),
    "--neural-grace-ticks", str(CONFIG["neural_grace_ticks"]),
    "--neural-grace-floor", str(CONFIG["neural_grace_floor"]),
    "--modular-fraction", str(CONFIG["modular_fraction"]),
    "--modular-max-blocks", str(CONFIG["modular_max_blocks"]),
    "--structural-rate", str(CONFIG["structural_rate"]),
    "--world-refresh-every", str(CONFIG["world_refresh_every"]),
    "--checkpoint-every", str(CONFIG["checkpoint_every"]),
    "--checkpoint-limit", str(CONFIG["checkpoint_limit"]),
    "--log-every", str(CONFIG["log_every"]),
    "--output-dir", str(WORK / "run"),
]
if CONFIG["harshness"] is not None:
    args += ["--harshness", str(CONFIG["harshness"])]
if CONFIG.get("action_search_depth") is not None:
    args += ["--action-search-depth", str(CONFIG["action_search_depth"])]
if CONFIG.get("drive_injection_scale") is not None:
    args += ["--drive-injection-scale", str(CONFIG["drive_injection_scale"])]
if CONFIG.get("tap_cue_threshold") is not None:
    args += ["--tap-cue-threshold", str(CONFIG["tap_cue_threshold"])]
if CONFIG.get("tap_cue_drift") is not None:
    args += ["--tap-cue-drift", str(CONFIG["tap_cue_drift"])]
if CONFIG.get("combine_intent_window_scale") is not None:
    args += ["--combine-intent-window-scale", str(CONFIG["combine_intent_window_scale"])]
if CONFIG.get("exploration_floor") is not None:
    args += ["--exploration-floor", str(CONFIG["exploration_floor"])]
if CONFIG["quiet_events"]:
    args += ["--quiet-events"]

env_marker = WORK / "config_used.json"
env_marker.write_text(json.dumps(CONFIG, indent=2))

subprocess.run(args, check=True, cwd=str(SRC))

# Keep the output bundle small and analysis-ready: events (aggregates),
# champion checkpoints, and the run summary - drop story logs.
for run_dir in (WORK / "run").iterdir():
    for noisy in ("story_events.jsonl",):
        target = run_dir / noisy
        if target.exists():
            target.unlink()
print("DONE", flush=True)
